student_count = 11
puts "The students of Makers Academy"
puts "----------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex Delarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "The Joker"
puts "Joffrey Batatheon"
puts "Norman Bates"
puts "Overall, we have #{student_count} great students"
